name: Pull Request CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Check code style
        run: bun format:check

      - name: Lint
        run: bun lint

      - name: Built Next.js site
        run: bun run build
