name: Get Added Files on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  get-added-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Action Script
        run: bun build scripts/post-merge.ts --target node --outdir ./scripts

      - name: Run Action script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/post-merge.js')
            await script({ github, context, core })
